#!/usr/bin/env bun
// Reads all university-orgs CSVs and writes INSERT OR REPLACE SQL.
// Handles the many CSV format variants by fuzzy column resolution.
//
// CSV column semantics (regardless of column name):
//   name      → org name
//   type      → org type (Student Org, Lab, etc.)
//   category  → space category (Rockets, Satellites, etc.)
//   conf_col  → relevance level (Direct / Strongly Adjacent / Loosely Adjacent)
//                 may be text or numeric (1/2/3)
//   desc_col  → relevance description / internal notes → stored as `confidence`
//   website   → org URL

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, basename } from "path";

const ROOT = join(import.meta.dir, "..");
const CSV_DIR = join(ROOT, "data", "university-orgs-csv");
const OUT_FILE = join(ROOT, "scripts", "seed-orgs.sql");

function parseCSV(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuote = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuote) {
      if (ch === '"' && text[i + 1] === '"') {
        field += '"';
        i++;
      } else if (ch === '"') {
        inQuote = false;
      } else {
        field += ch;
      }
    } else {
      if (ch === '"') {
        inQuote = true;
      } else if (ch === ",") {
        row.push(field);
        field = "";
      } else if (ch === "\n") {
        row.push(field);
        field = "";
        if (row.some((c) => c !== "")) rows.push(row);
        row = [];
      } else if (ch !== "\r") {
        field += ch;
      }
    }
  }
  if (field || row.length) {
    row.push(field);
    if (row.some((c) => c !== "")) rows.push(row);
  }
  return rows;
}

function findCol(header: string[], ...candidates: string[]): number {
  for (const c of candidates) {
    const i = header.indexOf(c);
    if (i !== -1) return i;
  }
  return -1;
}

function numericToRelevance(val: string): string {
  if (val === "1") return "Direct";
  if (val === "2") return "Strongly Adjacent";
  if (val === "3") return "Loosely Adjacent";
  return val; // already a string like "Direct"
}

function sqlStr(val: string | null | undefined): string {
  if (val === null || val === undefined || val.trim() === "") return "NULL";
  return "'" + val.replace(/'/g, "''") + "'";
}

const files = readdirSync(CSV_DIR)
  .filter((f) => f.endsWith(".csv"))
  .sort();

const lines: string[] = [
  "-- Auto-generated by scripts/seed-orgs.ts — do not edit by hand",
  "-- Run: wrangler d1 execute app-database-pranav --local --config .alchemy/local/wrangler.jsonc --file ../../scripts/seed-orgs.sql",
  "",
];

let totalOrgs = 0;

for (const file of files) {
  const slug = basename(file, ".csv").trim();
  const text = readFileSync(join(CSV_DIR, file), "utf-8");
  const rows = parseCSV(text);
  if (rows.length < 2) continue;

  const header = rows[0].map((h) => h.trim().toLowerCase());

  const nameIdx = findCol(header, "name", "official_name");
  const typeIdx = findCol(header, "type", "organization_type");
  const categoryIdx = findCol(header, "category", "space_category");
  // Relevance level → stored as `relevance`
  const confIdx = findCol(
    header,
    "confidence",
    "confidence_level",
    "confidence_rating",
  );
  // Relevance description → stored as `confidence` (internal)
  const descIdx = findCol(
    header,
    "relevance",
    "relevance_explanation",
    "relevance_department",
  );
  // Website URL
  const urlIdx = findCol(
    header,
    "direct link",
    "direct_link",
    "website_url",
    "official_page_link",
    "official_url",
  );

  for (const row of rows.slice(1)) {
    const name = nameIdx >= 0 ? row[nameIdx]?.trim() : undefined;
    if (!name || name.startsWith("---") || name.startsWith("===")) continue;

    const type = typeIdx >= 0 ? (row[typeIdx]?.trim() ?? "") : "";
    const category = categoryIdx >= 0 ? (row[categoryIdx]?.trim() ?? "") : "";
    const rawConf = confIdx >= 0 ? (row[confIdx]?.trim() ?? "") : "";
    const relevance = numericToRelevance(rawConf);
    const confidence = descIdx >= 0 ? (row[descIdx]?.trim() ?? "") : "";
    const website = urlIdx >= 0 ? (row[urlIdx]?.trim() ?? "") : "";

    lines.push(
      `INSERT OR REPLACE INTO organization (institution_id, name, type, category, relevance, confidence, website) ` +
        `VALUES ((SELECT id FROM institution WHERE slug = ${sqlStr(slug)}), ` +
        `${sqlStr(name)}, ${sqlStr(type)}, ${sqlStr(category)}, ` +
        `${sqlStr(relevance) === "NULL" ? "'Direct'" : sqlStr(relevance)}, ` +
        `${sqlStr(confidence)}, ${sqlStr(website)});`,
    );
    totalOrgs++;
  }
}

writeFileSync(OUT_FILE, lines.join("\n") + "\n");
console.log(`Wrote ${totalOrgs} organization rows → scripts/seed-orgs.sql`);
